export const en = {
  welcome: "welcome",
  name: "name",
  loans: "loans",
  bills: "bills",
  Account: "Account",
  homepage: "Homepage",
  mine: "Mine",
  // excel
  AlphaCash: 'AlphaCash',
  AlphaCashBrief:'AlphaCash is a safe, simple and fast online loan with a variety of loan products. You can always find a loan product that suits you.',
  PrivacyPolicy: 'For more information, please see the Privacy Policy and Terms&Conditions.',
  Agree:"Agree",
  Reject:'Reject',
  RateUs: 'Rate Us',
  GoodReview:'You have completed the application and are reviewing it. The payment will be released after a while. If you think it is good, remember to give it a good review.',
  RepaymentTips: "Repayment Tips",
  RepaymentWords: 'In order to avoid overdue behavior, you can turn on the repayment reminder, which will remind you to repay the repayment in time on [the day before the due date and the day] and increase the amount',
  NoteSettings: 'Note: If you need to turn off the reminder, you can turn it off in My/Settings',
  NoOpen:"No Open",
  OpenNow: "Open Now",
  FastDisburseLoanRepayment:'Fast Disburse, Loan & Repayment',
  MaxAmount: 'Max Amount',
  GetLoan: 'Get Loan',
  Register: 'Register',
  CompleteInfo: 'Complete Info',
  DisburseAmount: "Disburse Amount",
  Advantage: 'Advantage',
  HighAmount: 'High Amount',
  FastDisburse: 'Fast Disburse',
  FlexibleRepayment: 'Flexible Repayment',
  AntiFraudTips:'Anti-fraud Tips: Do not trust the repayment provided by others, please follow the transaction method prompted by the App to repay, other payment methods are counterfeit, avoid being deceived!!!',
  BenefitsOfRepayOnTime: "Benefits of repay on time",
  HigherAmount: 'Higher Amount',
  OpportunityForExemption: "Opportunity for exemption",
  UnlockMoreLoanTerm:"Unlock more Loan Term",
  ViewDetails: "View Details",
  RepayNow: 'Repay Now',
  EditNow: 'Edit Now',
  AccountErrorMessage:'Because your receiving account number is wrong, the payment cannot be made successfully, please edit the receiving account number!',
  IDPhotoErrorMessage:'We were unable to verify your identity because your ID photo is blurry, please upload it again so we can verify!',
  FacePhotoErrorMessage:'Because your face recognition is blurred, we cannot check your information, please re-face recognition so that we can verify',
  FaceRecognitionNow:'Face Recognition Now',
  ImproveYourPassRate:'Please follow the instructions to complete the face recognition action and improve your pass rate!',
  InReview:'In Review',
  Disbursing:'Disbursing',
  DisburseFailed:'Disburse Failed',
  Approved: 'Approved',
  Reject:'Reject',
  Overdue:'Overdue',
  Repaid:'Repaid',
  LoanAmount:'Loan Amount',
  LoanTerm:'Loan Term',
  Fee: 'Fee',
  Markup:'Markup',
  DisburseAmount:'Disburse Amount',
  'Due Date':'Due Date',
  'Lump Sum Repayment Amount':'Lump Sum Repayment Amount',
  'Collection Account':'Collection Account',
  'Face Recognition':'Face Recognition',
  'Please Choose':'Please Choose',
  'Please Identify':'Please Identify',
  'Passed':'Passed',
  'Failed, Please Try Again':'Failed, Please Try Again',
  'Try Again Now':'Try Again Now',
  'Agree Loan Agreement':'Agree Loan Agreement',
  'Late Payment Charges':'Late Payment Charges',
  'Confirm Payment Info':'Confirm Payment Info',
  'Disburse Now':'Disburse Now',
  'I have read and fully understood the Markup charges and terms of the loan product, and I agree that when the loan is approved, the funds will be transferred directly to the account I provided!':'I have read and fully understood the Markup charges and terms of the loan product, and I agree that when the loan is approved, the funds will be transferred directly to the account I provided!',
  'Kind Tips':'Kind Tips',
  "KindTips1": '1.Cooling off period: If you regret applying for a loan,please contact us promptly and repay the principal within24 hours.According to company regulations, we will cancel your loan application for free!',
  "KindTips2":"2.Remember to repay the loan in time, if you fail to repay the loan on time, you will be fined according to the  Late Payment Charges rate of 2%/day!",
  "KindTips3":"3. Name of Principal Executive Officer for Loan Processing: xxxx  Contact email: xxxxt@xx.com  Address: XXXXXXXX",
  'Credit Approval Fee':'Credit Approval Fee',
  'Service Fee':'Service Fee',
  'System fee':'System fee',
  'Processing Fee Charges':'Processing Fee Charges',
  'Any other charges':'Any other charges',
  'Apply Qualification':'Apply Qualification',
  'Terribly sorry,after evaluating you are currently not Qualification to apply, please apply again in another day!':'Terribly sorry,after evaluating you are currently not Qualification to apply, please apply again in another day!',
  'I Know':'I Know',
  'Bill':'Bill',
  'Current Bill':'Current Bill',
  'Old Bill':'Old Bill',
  'State':'State',
  'Apply Date':'Apply Date',
  'Loan Date':'Loan Date',
  'Repaid Amount':'Repaid Amount',
  'Repayment Date':'Repayment Date',
  'Repay on time, the credit limit will be higher and higher!':'Repay on time, the credit limit will be higher and higher!',
  'Use EasyPaisa for repayment': "Use EasyPaisa for repayment, operation instructions Click to view>':'Tips: Use EasyPaisa for repayment, operation instructions Click to view>",
  'Tips':'Tips',
  'Tip1': '1. Use PayPro to make repayment, operation instructions Click to view>>',
  "Tip2": '2. You can use bank apps or digital wallets to make repayments through PayPro ID, support the use of IBFT including all Pakistani banks and all Pakistani digital wallets.',
  Edit:'Edit',
  'Phone Number':'Phone Number',
  OTP:'OTP',
  'Get OTP':'Get OTP',
  'Log In':'Log In',
  'If the unregistered mobile phone number is verified, an account will be automatically created!':'If the unregistered mobile phone number is verified, an account will be automatically created!',
  'Agree Privacy Agreement and Terms&Service':'Agree Privacy Agreement and Terms&Service',
  'Certification Info': 'Certification Info',
  'Personal Info': 'Personal Info',
  'Work Info': 'Work Info',
  'Reference Contact':'Reference Contact',
  'Identity Info':  'Identity Info',
  'The information you fill in is only used for credit evaluation and will never be used for other purposes.We use encryption to ensure your information security!': 'The information you fill in is only used for credit evaluation and will never be used for other purposes.We use encryption to ensure your information security!',
  Name:'Name',
  'Date of Birth': 'Date of Birth',
  Gender: 'Gender',
  CNIC:'CNIC',
  Education:'Education',
  'Marital Status':'Marital Status',
  'Residential Address':'Residential Address',
  'Detailed Address':'Detailed Address',
  'Email':'Email',
  'Working Field':'Working Field',
  'Company Name':'Company Name',
  'Company Phone':'Company Phone',
  'Length Service':'Length Service',
  'Monthly Income':'Monthly Income',
  'Have Other Loans?':'Have Other Loans?',
  'Lending Institution':'Lending Institution',
  'Loan Amount':'Loan Amount',
  'Company Address':'Company Address',
  'Detailed Address':'Detailed Address',
  'Reference Relationship':'Reference Relationship',
  'Reference Name':'Reference Name',
  'Reference Number':'Reference Number',
  'Upload credential information, only for user identity verification, we will encrypt and store it, and it will never be used for other purposes!':'Upload credential information, only for user identity verification, we will encrypt and store it, and it will never be used for other purposes!',
  'CNIC Card':'CNIC Card',
  'CNIC Card Front':'CNIC Card Front',
  'CNIC Card Back':'CNIC Card Back',
  'Take photo with CNIC card in hand':'Take photo with CNIC card in hand',
  'Proof Employment':'Proof Employment',
  'Example':'Example',
  'Mobile Wallect Account':'Mobile Wallect Account',
  'Notice': 'Notice',
  "Notice1": '1. Please fill in your collection account number. When your application is approved, the loan will be issued to your collection account number. Please check the collection account number carefully to avoid unsuccessful payment;',
  "Notice2": '2. You can apply for the first loan after the receiving account is successfully added;',
  "Notice3": '3. When you fill in Jazzcash as the receiving account number, please fill in the Jazzcash account number that matches your CNIC, otherwise the payment will not be successful.',
  'bank account name':'bank account name',
  'Bank Account':'Bank Account',
  'Bank name':'Bank name',
  'Add Collection Account':'Add Collection Account',
  'Submit':'Submit',
  'Confirm Delete':'Confirm Delete',
  'Cancel':'Cancel',
  'Confirm':'Confirm',
  'Contact Us':'Contact Us',
  'Online Service':'Online Service',
  'Recommend':'Recommend',
  'Email':'Email',
  'Contact Number':'Contact Number',
  'Just upload any proof':'Just upload any proof',
  'Work Scene':'Work Scene',
  'Work Card':'Work Card',
  'Salary Statement':'Salary Statement',
  'Other Certificates':'Other Certificates',
  'CNIC has been bound by others, please re-enter':'CNIC has been bound by others, please re-enter',
  'Please fill in the complete info':'Please fill in the complete info',
  'Settings':'Settings',
  'Repayment Tips':'Repayment Tips',
  'Language':'Language',
  'Privacy Policy':'Privacy Policy',
  'Version':'Version',
  'Log Out':'Log Out',
  'Are you sure to log out?': 'Are you sure to log out?',
  'Collection Account':'Collection Account',
  'Are you sure you want to turn off the repayment tips?':'Are you sure you want to turn off the repayment tips?',
  '[AlphaCash]The loan you applied for is about to expire, please repay it in time!':'[AlphaCash]The loan you applied for is about to expire, please repay it in time!',
  '[AlphaCash]The loan you applied for is due, and you must repay it in time today to avoid overdue!':'[AlphaCash]The loan you applied for is due, and you must repay it in time today to avoid overdue!',
  'Repayment reminder has been successfully turned on!':'Repayment reminder has been successfully turned on!',
  'Bill Details':'Bill Details',
  'Mine':'Mine',
  'Home':'Home',
  'Get Loan':'Get Loan',
  'Call':'Call',
  'Next':'Next',
  'YES':'Yes',
  'NO':'No',
  'Days':'Days',
  'Return':'Return',
  'Province':'Province',
  'City':'City',
};
