export const urdu = {
  welcome: "欢迎",
  name: "姓名",
  loans: "贷款",
  bills: "账单",
  Account: "账户",
  homepage: "首页",
  mine: "我的",
  // excel
  AlphaCash: "AlphaCash",
  AlphaCashBrief:
    "ایک محفوظ، آسان اور تیز آن لائن قرض ہے جو مختلف قسم کے قرض کی مصنوعات پیش کرتا ہے۔ آپ ہمیشہ قرض کی مصنوعات تلاش کرسکتے ہیں جو آپ کے مطابق ہو۔",
  PrivacyPolicy:
    "مزید معلومات کے لیے، براہ کرم پرائیویسی پالیسی اور شرائط و ضوابط دیکھیں",
  Agree: "متفق",
  Reject: "مسترد",
  RateUs: "ہمیں درجہ دیں",
  GoodReview:
    "آپ نے درخواست مکمل کر لی ہے اور اس کا جائزہ لے رہے ہیں۔ ادائیگی تھوڑی دیر کے بعد جاری کر دی جائے گی۔ اگر آپ کو لگتا ہے کہ یہ اچھا ہے تو اس کا اچھا جائزہ لینا یاد رکھیں!",
  RepaymentTips: "ادائیگی کی تجاویز",
  RepaymentWords:
    "زائد المیعاد رویے سے بچنے کے لیے، آپ واپسی کی یاد دہانی کو آن کر سکتے ہیں، جو آپ کو یاد دلائے گا کہ [مقررہ تاریخ اور دن سے ایک دن پہلے] کو وقت پر ادائیگی کی جائے اور رقم میں اضافہ ہو جائے!",
  NoteSettings:
    "نوٹ: اگر آپ کو یاد دہانی کو بند کرنے کی ضرورت ہے، تو آپ اسے My/Settings میں بند کر سکتے ہیں۔",
  NoOpen: "منسوخ کریں۔",
  OpenNow: "ابھی یاد دہانی آن کریں۔",
  FastDisburseLoanRepayment: "تیزی سے آمد، قرض اور ادائیگی",
  MaxAmount: "زیادہ سے زیادہ رقم",
  GetLoan: "فوری طور پر درخواست دیں",
  Register: "رجسٹر کریں",
  CompleteInfo: "مکمل معلومات",
  DisburseAmount: "رقم حاصل کریں",
  Advantage: "فائدہ",
  HighAmount: "زیادہ مقدار",
  FastDisburse: "تیز ادائیگی",
  FlexibleRepayment: "لچکدار ادائیگی",
  "Anti-fraud Tips": "اینٹی فراڈ ٹپس",
  AntiFraudTips:
    "دوسروں کی طرف سے فراہم کردہ ادائیگی کے طریقوں پر بھروسہ نہ کریں، براہ کرم ایپ کی جانب سے ادائیگی کے لیے بتائے گئے لین دین کے طریقہ کار پر عمل کریں، ادائیگی کے دیگر طریقے جعلی ہیں، دھوکہ دہی سے بچیں!!!",
  BenefitsOfRepayOnTime: "وقت پر ادائیگی کے فوائد",
  HigherAmount: "زیادہ مقدار",
  OpportunityForExemption: "ادائیگی کی رقم کو کم کرنے کا موقع",
  UnlockMoreLoanTerm: "مزید قرض کے چکروں کو غیر مقفل کریں۔",
  ViewDetails: "تفصیلات چیک کریں",
  RepayNow: "فوری طور پر ادا کریں",
  EditNow: "ابھی ترمیم کریں۔",
  AccountErrorMessage:
    "چونکہ آپ کا وصول کرنے والا اکاؤنٹ نمبر غلط ہے، اس لیے ادائیگی کامیابی سے نہیں کی جا سکتی، براہ کرم وصول کرنے والے اکاؤنٹ نمبر میں ترمیم کریں۔",
  IDPhotoErrorMessage:
    "ہم آپ کی شناخت کی تصدیق نہیں کر سکے کیونکہ آپ کی شناختی تصویر دھندلی ہے، براہ کرم اسے دوبارہ اپ لوڈ کریں تاکہ ہم تصدیق کر سکیں",
  FacePhotoErrorMessage:
    "چونکہ آپ کے چہرے کی شناخت دھندلی ہے، اس لیے ہم آپ کی معلومات کی جانچ نہیں کر سکتے، براہ کرم دوبارہ چہرے کی شناخت کریں تاکہ ہم تصدیق کر سکیں",
  FaceRecognitionNow: "چہرے کی فوری شناخت",
  ImproveYourPassRate:
    "چہرے کی شناخت کی کارروائی مکمل کرنے اور پاس کی شرح کو بہتر بنانے کے لیے براہ کرم ہدایات پر عمل کریں!",
  InReview: "زیر جائزہ",
  Disbursing: "ادائیگیاں",
  DisburseFailed: "ادائیگی ناکام",
  Approved: "منظورشدہ",
  Reject: "مسترد",
  Overdue: "زائد المیعاد",
  Repaid: "ادا کیا",
  LoanAmount: "قرضے کی رقم",
  LoanTerm: "قرض کی مدت",
  Fee: "فیس",
  Markup: "مارک اپ",
  DisburseAmount: "تقسیم کی رقم",
  "Due Date": "اخری تاریخ",
  "Lump Sum Repayment Amount": "یکمشت واپسی کی رقم",
  "Collection Account": "کلیکشن اکاؤنٹ",
  "Face Recognition": "چہرے کی شناخت",
  "Please Choose": "براہ کرم منتخب کریں۔",
  "Please Identify": "براہ کرم شناخت کریں۔",
  Passed: "گزر گیا",
  "Failed, Please Try Again": "ناکام، براہ کرم دوبارہ کوشش کریں۔",
  "Try Again Now": "ابھی دوبارہ کوشش کریں۔",
  "Agree Loan Agreement": "قرض کے معاہدے سے اتفاق کریں۔",
  "Late Payment Charges": "تاخیر سے ادائیگی کے چارجز",
  "Confirm Payment Info": "ادائیگی کی معلومات کی تصدیق کریں۔",
  "Disburse Now": "براہ راست ادائیگی",
  "I have read and fully understood the Markup charges and terms of the loan product, and I agree that when the loan is approved, the funds will be transferred directly to the account I provided!":
    "میں نے قرض کی مصنوعات کے سود کے چارجز اور شرائط کو پڑھ لیا ہے اور پوری طرح سمجھ لیا ہے، اور اس بات سے اتفاق کرتا ہوں کہ قرض کی منظوری کے بعد، فنڈز براہ راست میرے فراہم کردہ اکاؤنٹ میں منتقل کیے جائیں گے!",
  "Kind Tips": "مہربان تجاویز",
  KindTips1: `"طرح کے مشورے:
  کولنگ آف پیریڈ: اگر آپ کو قرض کے لیے درخواست دینے پر افسوس ہے، تو براہ کرم ہم سے بروقت رابطہ کریں اور 24 گھنٹے کے اندر پرنسپل کی ادائیگی کریں۔ کمپنی کے ضوابط کے مطابق، ہم آپ کے قرض کی درخواست مفت میں منسوخ کر دیں گے! "`,
  KindTips2:
    "قرض کی بروقت ادائیگی کرنا یاد رکھیں، اگر آپ قرض کی بروقت ادائیگی نہیں کرتے ہیں، تو آپ پر 2% فی دن کی لیٹ فیس کی شرح سے جرمانہ عائد کیا جائے گا!",
  KindTips3: `"پرنسپل لون پروسیسنگ ایگزیکٹو کا نام: xxxx
  ای میل سے رابطہ کریں: xxxxt@xx.com
  پتہ: XXXXXXXX"""`,
  "Credit Approval Fee": "کریڈٹ کی منظوری کی فیس",
  "Service Fee": "خدمت کا محاوضہ",
  "System fee": "سسٹم فیس",
  "Processing Fee Charges": "ہینڈلنگ فیس",
  "Any other charges": "کوئی دوسری فیس",
  "Apply Qualification": "پٹیشن فارم",
  "Terribly sorry":
    "میں بہت معذرت خواہ ہوں، تشخیص کے بعد آپ فی الحال درخواست دینے کے اہل نہیں ہیں، براہ کرم کسی اور دن میں دوبارہ درخواست دیں",
  "I Know": "میں سمجھ گیا، اچھا",
  Bill: "بل",
  "Current Bill": "موجودہ بل",
  "Old Bill": "تاریخی بل",
  State: "حالت",
  "Apply Date": "درخواست کی تاریخ",
  "Loan Date": "قرض کی تاریخ",
  "Repaid Amount": "ادا کی گئی رقم",
  "Repayment Date": "ادائیگی کی تاریخ",
  "Repay on time, the credit limit will be higher and higher!":
    "وقت پر ادائیگی کریں، کریڈٹ کی حد زیادہ سے زیادہ ہوگی۔",
  "Use EasyPaisa for repayment":
    "یاد دہانی: ادائیگی کے لیے ایزی پیسہ استعمال کریں، آپریشن کی ہدایات دیکھنے کے لیے کلک کریں>",
  Tips: "اشارہ:",
  Tip1: "1. ادائیگی کرنے کے لیے PayPro استعمال کریں، آپریشن کی ہدایات دیکھنے کے لیے کلک کریں>>",
  Tip2: "2. آپ PayPro ID کے ذریعے ادائیگی کرنے کے لیے بینک ایپس یا ڈیجیٹل والیٹس استعمال کر سکتے ہیں، تمام پاکستانی بینکوں اور تمام پاکستانی ڈیجیٹل والیٹس سمیت IBFT کے استعمال کی حمایت کر سکتے ہیں",
  Edit: "نظر ثانی کریں۔",
  "Phone Number": "فون نمبر",
  OTP: "تصدیقی کوڈ",
  "Get OTP": "تصدیقی کوڈ حاصل کریں۔",
  "Log In": "لاگ ان کریں",
  "If the unregistered mobile phone number is verified, an account will be automatically created!":
    "اگر غیر رجسٹرڈ موبائل فون نمبر کی تصدیق ہو جاتی ہے تو ایک اکاؤنٹ خود بخود بن جائے گا۔",
  "Agree Privacy Agreement and Terms&Service":
    "رازداری کے معاہدے اور سروس کی شرائط سے اتفاق کریں۔",
  "Certification Info": "سرٹیفیکیشن کی معلومات",
  "Personal Info": "ذاتی معلومات",
  "Work Info": "کام کی معلومات",
  "Reference Contact": "ہنگامی رابطے",
  "Identity Info": "شناخت کی معلومات",
  "information security":
    "آپ جو معلومات پُر کرتے ہیں وہ صرف کریڈٹ کی تشخیص کے لیے استعمال ہوتی ہے اور اسے کبھی دوسرے مقاصد کے لیے استعمال نہیں کیا جائے گا۔ ہم آپ کی معلومات کو محفوظ رکھنے کے لیے خفیہ کاری کا استعمال کرتے ہیں!",
  Name: "نام",
  "Date of Birth": "پیدائش کی تاریخ",
  Gender: "صنف",
  CNIC: "CNIC",
  Education: "تعلیمی قابلیت",
  "Marital Status": "ازدواجی حیثیت",
  "Residential Address": "رہائشی پتے",
  "Detailed Address": "تفصیلی پتہ",
  Email: "ای میل",
  "Working Field": "پیشہ",
  "Company Name": "کمپنی کا نام",
  "Company Phone": "کمپنی کا فون",
  "Length Service": "کام کے اوقات",
  "Monthly Income": "ماہانہ آمدنی",
  "Have Other Loans?": "کیا دوسرے قرضے ہیں؟",
  "Lending Institution": "قرض دینے والا ادارہ",
  "Loan Amount": "قرضے کی رقم",
  "Company Address": "کمپنی ایڈریس",
  "Detailed Address": "تفصیلی پتہ",
  "Reference Relationship": "حوالہ رشتہ",
  "Reference Name": "نام کا حوالہ",
  "Reference Number": "حوالہ نمبر",
  "Upload credential information, only for user identity verification, we will encrypt and store it, and it will never be used for other purposes!":
    "اسناد کی معلومات اپ لوڈ کریں، صرف صارف کی شناخت کی توثیق کے لیے، ہم اسے انکرپٹ اور اسٹور کریں گے، اور اسے کبھی دوسرے مقاصد کے لیے استعمال نہیں کیا جائے گا!",
  "CNIC Card": "CNIC کارڈ",
  "CNIC Card Front": "CNIC کارڈ سامنے",
  "CNIC Card Back": "CNIC کارڈ واپس",
  "Take photo with CNIC card in hand": "CNIC کارڈ ہاتھ میں لے کر تصویر لیں۔",
  "Proof Employment": "ثبوت روزگار",
  Example: "مثال",
  "Mobile Wallect Account": "موبائل والیٹ اکاؤنٹ",
  Notice: "نوٹس",
  Notice1:
    "1. براہ کرم اپنا کلیکشن اکاؤنٹ نمبر پُر کریں۔ جب آپ کی درخواست منظور ہو جائے گی، آپ کے کلیکشن اکاؤنٹ نمبر پر قرض جاری کر دیا جائے گا۔ ناکام ادائیگی سے بچنے کے لیے براہ کرم کلیکشن اکاؤنٹ نمبر کو احتیاط سے چیک کریں۔",
  Notice2:
    "2. وصول کنندہ اکاؤنٹ کامیابی سے شامل ہونے کے بعد آپ پہلے قرض کے لیے درخواست دے سکتے ہیں۔",
  Notice3:
    "3. جب آپ Jazzcash کو وصول کنندہ اکاؤنٹ نمبر کے طور پر پُر کرتے ہیں، تو براہ کرم Jazzcash اکاؤنٹ نمبر کو پُر کریں جو آپ کے CNIC سے مماثل ہو، بصورت دیگر ادائیگی کامیاب نہیں ہوگی۔",
  "bank account name": "بینک اکاؤنٹ کا نام",
  "Bank Account": "بینک اکاؤنٹ",
  "Bank name": "بینک کا نام",
  "Add Collection Account": "وصول کرنے والا اکاؤنٹ شامل کریں۔",
  Submit: "جمع کرائیں",
  "Confirm Delete": "حذف کی تصدیق کریں۔",
  Cancel: "منسوخ کریں۔",
  Confirm: "ضرور",
  "Contact Us": "ہم سے رابطہ کریں۔",
  "Online Service": "آن لائن سروس",
  Recommend: "سفارش کریں",
  Email: "ای میل سے رابطہ کریں۔",
  "Contact Number": "رابطہ نمبر",
  "Just upload any proof": "بس کوئی ثبوت اپ لوڈ کریں۔",
  "Work Scene": "کام کا منظر",
  "Work Card": "نام کارڈ",
  "Salary Statement": "تنخواہ کا بیان",
  "Other Certificates": "	دیگر سرٹیفکیٹ",
  "CNIC has been bound by others, please re-enter	CNIC":
    "CNIC دوسروں کے ذریعے پابند کیا گیا ہے، براہ کرم دوبارہ درج کریں۔",
  "Please fill in the complete info": "براہ کرم مکمل معلومات پُر کریں۔",
  Settings: "قائم کریں",
  "Repayment Tips": "ادائیگی کی یاد دہانی",
  Language: "	زبان کی ترتیبات",
  "Privacy Policy": "	رازداری کی پالیسی",
  Version: "	موجودہ ورژن",
  "Log Out": "	باہر جائیں",
  "Are you sure to log out?": "کیا آپ کو لاگ آؤٹ کرنا یقینی ہے؟",
  "Collection Account": "جمع اکاؤنٹ",
  "Are you sure you want to turn off the repayment tips?":
    "کیا آپ واقعی ادائیگی کی یاد دہانی کو بند کرنا چاہتے ہیں؟",
  "The loan you applied for is about to expire, please repay it in time!":
    "[AlphaCash] آپ نے جس قرض کے لیے درخواست دی ہے اس کی میعاد ختم ہونے کو ہے، براہ کرم اسے وقت پر ادا کریں!",
  "The loan you applied for is due, and you must repay it in time today to avoid overdue!":
    "[AlphaCash] آپ نے جس قرض کے لیے درخواست دی ہے وہ واجب الادا ہے، اور واجب الادا ہونے سے بچنے کے لیے آپ کو اسے آج ہی وقت پر ادا کرنا ہوگا!",
  "Repayment reminder has been successfully turned on!":
    "ادائیگی کی یاد دہانی کامیابی کے ساتھ آن کر دی گئی ہے۔",

  "Bill Details": "بل کی تفصیلات",
  Mine: "ذاتی مرکز",
  Home: "گھر",
  "Get Loan": "قرض حاصل کریں۔",
  Call: "ڈائل",
  Next: "اگلے",
  YES: "جی ہاں",
  NO: "نہیں",
  Days: "دن",
  Return: "واپسی",
  Province: "صوبہ",
  City: "شہر",
  Close: "بندش",
  "For more information": "مزید معلومات کے لیے، براہ کرم دیکھیں",
  "Privacy Policy": "رازداری کی پالیسی",
  "Terms&Conditions": "شرائط و ضوابط",
  "Key Executive For Loan Handling officer Name":
    "پرنسپل لون پروسیسنگ ایگزیکٹو کا ",
  "Contact Email": "ای میل سے رابطہ کریں",
  Address: "پتہ",
  "Please face the screen": "براہ کرم اسکرین کا سامنا کریں۔",
  "Please close your eyes and then blink your eyes":
    "براہ کرم اپنی آنکھیں بند کریں اور پھر آنکھیں جھپکائیں۔",
  "Please shake left, then right": "براہ مہربانی بائیں ہلائیں، پھر دائیں",
  Apply: "ایپلی کیشن",
  Loading: "لوڈنگ...",
  "Successful face recognition": "Successful face recognition",
  "modify successfully": "modify successfully",
  APR: "APR",
  "Repayment via Easypaisa": "Repayment via Easypaisa",
  "Account Name": "کھاتے کا نام",
  "Consumer ID": "صارف کی شناخت",
  "Kind Tips": "اشارہ",
  "Use EasyPaisa to make repayment, the operation instructions": "EasyPaisa کا استعمال کرتے ہوئے ادائیگی، ہدایات",
  "click to view>>": "دیکھنے کے لیے کلک کریں >>",
  "EasyPaisa Repayment Operation Instructions": "%{type} ادائیگی کے آپریشن کی ہدایات",
  "Operating steps": "آپریشن کے اقدامات",
  "Log in EasyPaisa Account and then enter Consumer ID": "لاگ ان کریں 【%{type} اکاؤنٹ】>>تلاش پر کلک کریں اور 【AlphaCash】>> درج کریں اور پھر 【کنزیومر آئی ڈی】 درج کریں۔",
  "As shown in the example below": "جیسا کہ ذیل کی مثال میں دکھایا گیا ہے۔",
  "Log in EasyPaisa Account": "لاگ ان کریں 【%{type} اکاؤنٹ】",
  "Click Search , enter AlphaCash, and select AlphaCash": "[تلاش] پر کلک کریں، [AlphaCash] درج کریں، اور [AlphaCash] کو منتخب کریں",
  "Enter Consumer ID, click Next, and then click PAY NOW": "[کنزیومر آئی ڈی] درج کریں، [اگلا] پر کلک کریں، اور پھر [ابھی ادائیگی کریں] پر کلک کریں",
  "Repayment method": "ادائیگی کا طریقہ",
  "LoanAgreement":"Loan Agreement"
  };
